
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  displayImage: 'displayImage',
  neupId: 'neupId',
  type: 'type',
  createdOn: 'createdOn',
  status: 'status',
  moreDetails: 'moreDetails'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  portfolioId: 'portfolioId',
  accountId: 'accountId',
  role: 'role'
};

exports.Prisma.DomainScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  domain: 'domain',
  isPrimary: 'isPrimary'
};

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  tier: 'tier',
  modules: 'modules',
  icons: 'icons',
  domains: 'domains',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ownerAccountId: 'ownerAccountId',
  status: 'status',
  type: 'type'
};

exports.Prisma.ProfileScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  subject: 'subject',
  value: 'value'
};

exports.Prisma.ThemeScalarFieldEnum = {
  id: 'id',
  hideSitename: 'hideSitename',
  hideLogo: 'hideLogo',
  theme: 'theme',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PageScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  description: 'description',
  elements: 'elements',
  reactComponent: 'reactComponent',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PagePathScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  pageId: 'pageId',
  path: 'path',
  createdAt: 'createdAt'
};

exports.Prisma.SectionScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  type: 'type',
  content: 'content',
  source: 'source',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.TemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  imageUrl: 'imageUrl',
  previewUrl: 'previewUrl',
  category: 'category',
  type: 'type',
  status: 'status',
  usableOn: 'usableOn',
  content: 'content',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.DataSourceScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  type: 'type',
  methods: 'methods',
  url: 'url',
  headers: 'headers',
  connection: 'connection',
  data: 'data',
  datalistId: 'datalistId',
  createdAt: 'createdAt'
};

exports.Prisma.PageDataSourceBindingScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  pageId: 'pageId',
  sourceId: 'sourceId',
  methodName: 'methodName'
};

exports.Prisma.DatalistScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RedirectScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  from: 'from',
  to: 'to',
  type: 'type',
  created_by: 'created_by',
  created_on: 'created_on'
};

exports.Prisma.EnvironmentVariableScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  value: 'value',
  dataType: 'dataType',
  isPrivate: 'isPrivate',
  createdBy: 'createdBy',
  createdOn: 'createdOn'
};

exports.Prisma.SiteStructureScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  structure: 'structure',
  status: 'status',
  themeChanged: 'themeChanged',
  redirectsChanged: 'redirectsChanged',
  assetsChanged: 'assetsChanged',
  appBaseChanged: 'appBaseChanged',
  environmentsChanged: 'environmentsChanged',
  updatedAt: 'updatedAt'
};

exports.Prisma.DeploymentScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  structure: 'structure',
  status: 'status',
  theme: 'theme',
  redirects: 'redirects',
  siteProfile: 'siteProfile',
  environments: 'environments',
  attemptedOn: 'attemptedOn'
};

exports.Prisma.ServerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  publicIp: 'publicIp',
  privateIp: 'privateIp',
  privateKey: 'privateKey',
  serverType: 'serverType',
  platform: 'platform',
  provider: 'provider',
  isPrivate: 'isPrivate',
  username: 'username',
  basePath: 'basePath',
  appPath: 'appPath',
  storageUsed: 'storageUsed',
  storageTotal: 'storageTotal',
  storageUnit: 'storageUnit',
  portsOpen: 'portsOpen',
  serverConfigured: 'serverConfigured',
  defaultNginxConfigStatus: 'defaultNginxConfigStatus',
  createdOn: 'createdOn',
  expiresOn: 'expiresOn'
};

exports.Prisma.AllocationScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  assetId: 'assetId',
  username: 'username',
  deploymentPath: 'deploymentPath',
  storageAllocation: 'storageAllocation',
  port: 'port',
  allocatedStorage: 'allocatedStorage',
  allocatedOn: 'allocatedOn',
  status: 'status'
};

exports.Prisma.ServerLogScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  commandId: 'commandId',
  commandName: 'commandName',
  command: 'command',
  output: 'output',
  status: 'status',
  initiatedBy: 'initiatedBy',
  initiatedAt: 'initiatedAt',
  completedAt: 'completedAt'
};

exports.Prisma.ServerCommandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  commandTemplate: 'commandTemplate',
  parameters: 'parameters',
  preExecutionScript: 'preExecutionScript',
  allocatesPort: 'allocatesPort',
  portToReserve: 'portToReserve',
  type: 'type',
  danger: 'danger',
  nextCommands: 'nextCommands',
  createdAt: 'createdAt'
};

exports.Prisma.CodeFileScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  fileName: 'fileName',
  filePath: 'filePath',
  content: 'content',
  size: 'size',
  createdAt: 'createdAt'
};

exports.Prisma.LinkedAccountScalarFieldEnum = {
  id: 'id',
  account_id: 'account_id',
  platform: 'platform',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  scope: 'scope',
  providerUserId: 'providerUserId',
  providerUsername: 'providerUsername',
  authorized_on: 'authorized_on'
};

exports.Prisma.ApiTokenScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  name: 'name',
  tokenHash: 'tokenHash',
  tokenPrefix: 'tokenPrefix',
  createdAt: 'createdAt',
  lastUsed: 'lastUsed'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  description: 'description',
  order: 'order'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  name: 'name',
  email: 'email',
  role: 'role',
  imageUrl: 'imageUrl',
  order: 'order',
  teamId: 'teamId',
  permissions: 'permissions'
};

exports.Prisma.JobPostingScalarFieldEnum = {
  id: 'id',
  title: 'title',
  location: 'location',
  type: 'type',
  description: 'description',
  status: 'status',
  qualifications: 'qualifications',
  salary: 'salary',
  openings: 'openings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApplicantScalarFieldEnum = {
  id: 'id',
  jobId: 'jobId',
  name: 'name',
  email: 'email',
  resumeUrl: 'resumeUrl',
  coverLetter: 'coverLetter',
  status: 'status',
  appliedAt: 'appliedAt'
};

exports.Prisma.ErrorLogScalarFieldEnum = {
  id: 'id',
  message: 'message',
  stack: 'stack',
  componentStack: 'componentStack',
  source: 'source',
  details: 'details',
  timestamp: 'timestamp'
};

exports.Prisma.AppBaseBackupScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  fileName: 'fileName',
  fileType: 'fileType',
  content: 'content',
  backedUpAt: 'backedUpAt',
  backedUpBy: 'backedUpBy'
};

exports.Prisma.NewsArticleScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  content: 'content',
  author: 'author',
  imageUrl: 'imageUrl',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SyncRequestScalarFieldEnum = {
  id: 'id',
  source: 'source',
  destination: 'destination',
  data: 'data',
  status: 'status',
  requestedOn: 'requestedOn',
  attemptOn: 'attemptOn'
};

exports.Prisma.AssetModuleScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  title: 'title',
  status: 'status'
};

exports.Prisma.SyncerLogScalarFieldEnum = {
  id: 'id',
  appId: 'appId',
  clientId: 'clientId',
  type: 'type',
  content: 'content',
  createdOn: 'createdOn',
  status: 'status'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Account: 'Account',
  Role: 'Role',
  Domain: 'Domain',
  Asset: 'Asset',
  Profile: 'Profile',
  Theme: 'Theme',
  Page: 'Page',
  PagePath: 'PagePath',
  Section: 'Section',
  Template: 'Template',
  DataSource: 'DataSource',
  PageDataSourceBinding: 'PageDataSourceBinding',
  Datalist: 'Datalist',
  Redirect: 'Redirect',
  EnvironmentVariable: 'EnvironmentVariable',
  SiteStructure: 'SiteStructure',
  Deployment: 'Deployment',
  Server: 'Server',
  Allocation: 'Allocation',
  ServerLog: 'ServerLog',
  ServerCommand: 'ServerCommand',
  CodeFile: 'CodeFile',
  LinkedAccount: 'LinkedAccount',
  ApiToken: 'ApiToken',
  Team: 'Team',
  Member: 'Member',
  JobPosting: 'JobPosting',
  Applicant: 'Applicant',
  ErrorLog: 'ErrorLog',
  AppBaseBackup: 'AppBaseBackup',
  NewsArticle: 'NewsArticle',
  SyncRequest: 'SyncRequest',
  AssetModule: 'AssetModule',
  SyncerLog: 'SyncerLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
