'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createForm, type FormField } from '@/services/forms';
import { Button } from '@neup/components/ui/button';
import { Input } from '@neup/components/ui/input';
import { LinkButton } from '@neup/components/ui/link-button';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
const fieldTypes = ['text', 'email', 'number', 'tel', 'date', 'textarea', 'url'];
const toKey = (label: string, index: number) => label.toLowerCase().trim().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || `field_${index + 1}`;
export default function CreateFormPage() {
  const router = useRouter(); const [name, setName] = useState('Contact form'); const [fields, setFields] = useState<FormField[]>([{ name: 'name', label: 'Name', type: 'text', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'message', label: 'Message', type: 'textarea', required: true }]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (index: number, patch: Partial<FormField>) => setFields((current) => current.map((field, i) => i === index ? { ...field, ...patch } : field));
  const save = async () => { setSaving(true); setError(''); const result = await createForm({ name, slug: name, fields }); if (result.success) router.push('/inbox/forms'); else { setError(result.error || 'Unable to create form.'); setSaving(false); } };
  return <div className="w-full max-w-3xl space-y-6"><LinkButton variant="outlined" href="/inbox/forms"><ArrowLeft className="mr-2 h-4 w-4" />Back to Forms</LinkButton><div><h1 className="font-headline text-2xl font-semibold">Create form</h1><p className="text-sm text-muted-foreground">Define the fields your visitors can submit.</p></div><div className="space-y-6"><div className="space-y-2"><label className="text-sm font-medium">Form name</label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Contact form" /></div><div className="space-y-3"><div><h2 className="font-medium">Form fields</h2><p className="text-sm text-muted-foreground">The field key is generated from its label.</p></div>{fields.map((field, index) => <div key={index} className="space-y-3 rounded-md border p-3"><div className="flex items-end gap-2"><div className="flex-1 space-y-2"><label className="text-sm font-medium">Field {index + 1}</label><Input value={field.label} onChange={(e) => update(index, { label: e.target.value, name: toKey(e.target.value, index) })} placeholder="Full name" /></div><Button variant="ghost" type="button" onClick={() => setFields(fields.filter((_, i) => i !== index))}><Trash2 className="h-4 w-4" /></Button></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><label className="text-sm font-medium">Form field</label><Input value={field.name} readOnly /></div><div className="space-y-2"><label className="text-sm font-medium">Value type</label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={field.type} onChange={(e) => update(index, { type: e.target.value })}>{fieldTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></div></div></div>)}</div><Button variant="outlined" type="button" onClick={() => setFields([...fields, { name: `field_${fields.length + 1}`, label: '', type: 'text' }])}><Plus className="mr-2 h-4 w-4" />Add field</Button>{error && <p className="text-sm text-destructive">{error}</p>}<Button variant="solid" type="button" disabled={saving} onClick={save}>{saving ? 'Saving…' : 'Save form'}</Button></div></div>;
}
