import Link from 'next/link';
import { FileText, Inbox, List, Plus } from 'lucide-react';
import { getFormSubmissions } from '@/services/forms';
import { format } from 'date-fns';
import { appendProject } from '@/inapp/helpers/application-mode';

export default async function InboxPage({ searchParams }: { searchParams: Promise<{ project?: string }> }) {
  const { project } = await searchParams;
  const submissions = await getFormSubmissions();
  return <div className="w-full max-w-5xl space-y-6"><header><h1 className="font-headline text-2xl font-semibold">Inbox</h1><p className="text-sm text-muted-foreground">Contact form submissions from your projects.</p></header><div className="grid gap-4"><Link href={appendProject('/inbox/forms', project || null)} className="grid gap-4 rounded-lg border border-dashed bg-card px-5 py-4 transition-colors hover:border-primary hover:bg-primary/5 md:grid-cols-[auto_1fr] md:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted"><FileText className="h-5 w-5 text-muted-foreground" /></div><div><div className="font-medium">View Forms</div><div className="text-sm text-muted-foreground">Review and manage your forms.</div></div></Link><Link href={appendProject('/inbox', project || null)} className="grid gap-4 rounded-lg border border-dashed bg-card px-5 py-4 transition-colors hover:border-primary hover:bg-primary/5 md:grid-cols-[auto_1fr] md:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted"><List className="h-5 w-5 text-muted-foreground" /></div><div><div className="font-medium">View Field Submissions</div><div className="text-sm text-muted-foreground">Review submissions received from your forms.</div></div></Link><Link href={appendProject('/inbox/new', project || null)} className="grid gap-4 rounded-lg border border-dashed bg-card px-5 py-4 transition-colors hover:border-primary hover:bg-primary/5 md:grid-cols-[auto_1fr] md:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted"><Plus className="h-5 w-5 text-muted-foreground" /></div><div><div className="font-medium">Create a new Submission</div><div className="text-sm text-muted-foreground">Add a submission directly from the app.</div></div></Link></div>{submissions.length ? <div className="divide-y rounded-lg border bg-card">{submissions.map((item) => <Link key={item.id} href={`/inbox/${item.id}`} className="flex items-center justify-between p-4 hover:bg-muted/40"><div className="flex items-center gap-3"><Inbox className="h-4 w-4 text-muted-foreground" /><div><div className="font-medium">{item.form.name}</div><div className="text-sm text-muted-foreground">{format(item.postedOn, 'PPP p')}</div></div></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{item.status}</span></Link>)}</div> : <div className="rounded-lg border-2 border-dashed p-12 text-center text-muted-foreground">No submissions received yet.</div>}</div>;
}
